### ISSUE TITLE
callback after report downloaded is never executed

### ISSUE THREAD

**Issue by spac3-monkey** [CyberSource/cybersource-rest-samples-node#19]
running the example shows that the callback is never executed:

In the following example `Download report end.` never gets printed.

```js
  downloadReport(function () {
    console.log('Download report end.');
  });
```

**Comment by evghenii** [comment]
the responses and data are undefined, i changed to
`downloadReport(function(error, response)  
	{
		console.log(response)
		if(response)
		{
			console.log('Download report end.');
		}
	});`

**Comment by snavinch** [comment]
This has been fixed in our release, Please check.
